### PR TITLE
Clean

### PR DESCRIPTION
**Pull request by magomimmo**
Just a very stupid update to README and advanced sample regarding the lein cljsbuild clean task not being available anymore.

cheers

### CODE REVIEW

**Comment by mneise** [comment]
I think you might have confused `lein clean` with the `cljsbuild clean` subtask? All the changes you made are with regard to `lein clean` which is still a valid leiningen task.

**Comment by magomimmo** [comment]
Hi Maria,
sorry for the misunderstanding. 
In my own view, if there is no more a lein-cljsbuild clean subtask, `:hooks[leiningen.cljsbuild]` can't hook into the lein clean default task as it does with lein compile and lein jar tasks. lein clean does not get any new information from the cljsbuild configuration. Indeed you need to set the lein `clean-targets` directive if you want to clean outputs generated by cljsbuild into directories that are not included into the default target.  

the 1.0.4 release notes is a more clear about this. Anyway, I understand your point. 

The cljsbuild clean subtask is now a no-op. You should use lein clean to remove prior compilation results, and ensure that your output configurations direct those results into a Leiningen :clean-target (which includes./target by default) (gh-297)
Cheers
mimmo

**Comment by mneise** [comment]
Thank you for clarifying, makes sense now. And you are right, we don't even set up a hook for `lein clean`.

**Comment by mneise** [comment]
Thank you for the contribution :smiley:

**Comment by magomimmo** [comment]
you’re very welcome :-)

**Pull request merged**
