### PR TITLE
Add deps command

### LINKED ISSUE #479: Add `lein cljsbuild deps` task to install cljsbuild deps to local Maven repo
See:

https://github.com/technomancy/leiningen/issues/2055#issuecomment-332295586
https://github.com/technomancy/leiningen/issues/2055#issuecomment-332297983

This means there is no way to prepare an environment for an offline build without building project at least once. Please add `deps` task, or specify dependencies so that there is no such problem.

### PR DESCRIPTION
**Pull request by skuro**
Fixes #479

### CODE REVIEW

**Comment by FnTm** [comment]
This is wonderful! Any ideas on when this would get merged? Or whom we should ping to get that process going?

**Comment by skuro** [comment]
@FnTm this repo seems quite dormant I'm afraid

**Comment by mneise** [comment]
@skuro Thank you for the PR! Will take a look at it in the next days.

**Comment by skuro** [comment]
@mneise thanks for picking this up!

**Comment by FnTm** [comment]
@mneise Thank you for merging this! Any ideas on when this could be released in a new build? I'd like to start taking advantage of having this command sooner rather than later 🙂

**Comment by mneise** [comment]
@FnTm Wanted to release it the other day, but it will take a bit longer than expected, because I first need to update a few breaking dependencies. Sorry. Will try to get it out as soon as possible.

**Comment by FnTm** [comment]
@mneise Thanks for the heads-up! And thank you for taking the time to maintain the project! 🙌

**Comment by FnTm** [comment]
Hi @mneise , sorry to ping you, but I'm curious if we could expect a release sometime soon? Still itching to use the `deps` command.

**Comment by mneise** [comment]
@FnTm No worries, will try to get it done this week. Sorry it has taken so long.

**Comment by mneise** [comment]
@FnTm Just published version 1.1.8 which includes the new deps comand. Thank you for being so patient 😃

**Comment by FnTm** [comment]
woohoo! Thanks @mneise !

**Pull request merged**
