### PR TITLE
Restore functionality of plugin tests

### PR DESCRIPTION
**Pull request by avasenin**
Hi,

I met some issues when tried to contribute to lein-cljsbuild. *lein test* for plugin project exited without summary page. After some digging I discovered that the reason was in calling System/exit during run-local-projects calls and calling leiningen.core.main/abort without setting *exit-process?*. In other words when you run tests then leiningen run several of them, meet test with System/exit call and exit without any error message. So I decided to restore tests functionality first to be sure that I will not break anything.

I prepared a fix for this issue. Furthermore I fixed one fact with incorrect condition, upgraded midje to the latest version and clojure dependency to cljs-compat project.

CR plz

### CODE REVIEW

**Comment by cemerick** [comment]
Do you see the same problems when testing using the `bin/test-install.sh` script?

**Comment by avasenin** [comment]
Yep. 

I'm going to describe the found issues in more details to provide context below:

1) cljs-compat doesn't depend on clojure and doesn't have dependencies which depend on clojure. When `bin/test-install.sh` starts testing this project then it failed during compilation phase. I have no idea how it could work on your environment.

2) When `bin/test-install.sh` starts testing `plugin` project you could see some intermediate output in console but after that it meets test with `(System/exit)` at the end and exit from `lein test`. `bin/test-install.sh` skipping the rest tests on this project and move to example-project testing. So the issue occurs only in plugin project

I assume that plugin tests are broken from 2013 year when System/exit calls were added in d836402217d8ce26bddb0283c2fa9eefed66d5f5.

Moreover this fact from plugin project is broken from f5abefc4dcb763a6de280f98bca794115ec287c1 because signature of cljsbuild.test/run-tests was changed. 

```clojure
(let [parsed-commands [(config/parse-shell-command test-command)]]
  (fact "tests work correctly"
      (with-mocks
        (cljsbuild project "test")) => nil
      (with-mocks
        (cljsbuild project "test" test-command-id)) => nil
      (with-mocks
        (test-hook hook-success project)) => nil
      (with-mocks
        (test-hook hook-failure project)) => (throws Exception)
      (against-background
        (cljsbuild.crossover/crossover-macro-paths
          crossovers) => crossover-macros :times 0
        (cljsbuild.crossover/copy-crossovers
          crossover-path
          crossovers) => nil :times 1
        (cljsbuild.compiler/run-compiler
          source-paths
          crossover-path
          crossover-macros
          parsed-compiler
          anything
          incremental?
          assert?
          {}
          watch?) => nil :times 1
        (cljsbuild.test/run-tests parsed-commands) => nil :times 1)))
```

**Comment by avasenin** [comment]
Furthermore, it will be really nice to remove realpath call from `test-install.sh` because MacOS doesn't have realpath out of box. Probably we should just use `project_root=$(dirname $0)/..`. What do you think?

**Comment by avasenin** [comment]
Chas, I've rebased this branch to the latest master. One more test become broken in 1.0.6 when default value for :optimizations was eliminated (fixed during rebase).

It's pretty weird to see so high popular project with unstable tests. If you want I could write travis config for current test setup.

Thanks,

**Comment by cemerick** [comment]
Merged this to the develop/1.x branch.

Thank you for the patches, moving onto the next one. :-)

Just to give a little context (i.e. making excuses for myself :-P) re: why the tests were apparently doing nothing for so long:

1. I've generally found midje to be impenetrable.
2. Related, I've never seen much value in the ability to test whether and how many times some (usually private) function is called, esp. via the black magick that dynamic binding often is.
3. So much of the project is really just delivering some arguments to a CLJS compiler function. Testing this is sort of like writing unit tests to see if addition works.
4. The rest of the project (e.g. triggering auto builds, proper test execution, etc) isn't covered by tests at all, so I've always relied on dogfooding master on my own projects.

Of course, none of this is how things _should_ be, but ¯\_(ツ)_/¯

Anyway, thanks again for patching this up. I'll be cutting a `1.1.0-SNAPSHOT` shortly.

**Pull request closed without merging**
